version: "3"
services:
  api:
    image: vik-schedule
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      FLASK_APP: /usr/src/app/startapp.py
      FLASK_DEBUG: 1
      SQLALCHEMY_DATABASE_URI: postgresql://admin:password@db/vik-schedule-db
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      CLIENT_ROOT: $CLIENT_ROOT
      OAUTHLIB_INSECURE_TRANSPORT: $OAUTHLIB_INSECURE_TRANSPORT
    volumes:
      - type: bind
        source: ./api
        target: /usr/src/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: vik-schedule-db
    volumes:
      - db-data:/var/lib/postgresql/data 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 
volumes:
    db-data: