version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: tester
      POSTGRES_DB: vik-schedule-db-dev
    ports:
    - "5432:5432"