"""empty message

Revision ID: 147fe33380fc
Revises: e83b46e73923
Create Date: 2022-09-02 11:17:23.403499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147fe33380fc'
down_revision = 'e83b46e73923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture', sa.String(length=360), nullable=True))
    op.add_column('user', sa.Column('is_google_auth', sa.Boolean(), nullable=True))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('user', 'is_google_auth')
    op.drop_column('user', 'picture')
    # ### end Alembic commands ###
