"""empty message

Revision ID: 44ff45304b56
Revises: 147fe33380fc
Create Date: 2022-10-20 18:25:24.090981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ff45304b56'
down_revision = '147fe33380fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profile', 'class_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profile', sa.Column('class_time', sa.VARCHAR(length=600), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
