"""empty message

Revision ID: 90d12b13c36c
Revises: 3b461052aa19
Create Date: 2022-12-16 10:27:21.158783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d12b13c36c'
down_revision = '3b461052aa19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('contact', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'contact')
    # ### end Alembic commands ###
