"""empty message

Revision ID: ff578f0702fe
Revises: 44ff45304b56
Create Date: 2022-10-20 21:01:06.927991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff578f0702fe'
down_revision = '44ff45304b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_table', sa.Column('day', sa.String(length=10), nullable=True))
    op.drop_column('class_table', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_table', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('class_table', 'day')
    # ### end Alembic commands ###
