name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Start db container
        run: docker-compose up -f docker-compose.test.yaml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd api
          pip install -r requirements/dev.txt
          export FLASK_APP=startapp.py
          export FLASK_DEBUG=1
          export SQLALCHEMY_DATABASE_URI=postgresql://tester:password@db/0.0.0.0:5432
          export TEST=1

      - name: Setup database
        run: |
          flask db migrate
          flask db upgrade

      - name: Run tests
        run: |
          pytest